#! /bin/bash
# this script is used to generate input for analysispy (ancient_snakemake branch) from eager output
# eager ooutput generated by /Users/ad_loris/Nextcloud/keylab/projects/ak_ancient_zoonosis_project/pathogen_mapping/streptoccocus_lutetiensis/eager_calls.sh


mkdir -p /ptmp/iclight/snakemake/zooscreen/Streptoccocus_lutetiensis/ && cd /ptmp/iclight/snakemake/zooscreen/Streptoccocus_lutetiensis/
cp -r ~/keylab/snakemake/mapping/ . 
cp -r ~/keylab/snakemake/case/ .

# generate samples.csv
ls -1 /ptmp/iclight/eager/mapping/zooscreen/modern_Slutetiensis/results/deduplication/ | while read file_name 
    do echo "/ptmp/iclight/eager/mapping/zooscreen/modern_Slutetiensis/results/deduplication/$file_name/,$file_name,Slutetiensis_GCF900475675,${file_name}_rmdup,0,0" >> mapping/samples_modern.csv; done
ls -1 /ptmp/iclight/eager/mapping/zooscreen/Slutetiensis/results/deduplication/ | while read file_name
    do echo "/ptmp/iclight/eager/mapping/zooscreen/Slutetiensis/results/deduplication/$file_name/,$file_name,Slutetiensis_GCF900475675,${file_name}_rmdup,0,0" >> mapping/samples_modern.csv; done

head -n1 mapping/samples.csv > header.csv
cat header.csv mapping/samples_modern.csv > mapping/samples.csv
