#! /bin/bash
# this script is used to generate input for analysispy (ancient_snakemake branch) from eager output
# eager ooutput generated by /Users/ad_loris/Nextcloud/keylab/projects/ak_ancient_zoonosis_project/pathogen_mapping/erysipelothrix_rhusiopathiae/eager_calls.sh


mkdir -p /ptmp/iclight/snakemake/zooscreen/Erysipelothrix_rhusiopathiae/ && cd /ptmp/iclight/snakemake/zooscreen/Erysipelothrix_rhusiopathiae/
cp -r ~/keylab/snakemake/mapping/ . 
cp -r ~/keylab/snakemake/case/ .



ls -1 /ptmp/iclight/eager/mapping/zooscreen/modern_erysipelothrix_genbank/results/deduplication/ | while read file_name; do echo "/ptmp/iclight/eager/mapping/zooscreen/modern_erysipelothrix_genbank/results/deduplication/$file_name/,$file_name,Erysipelothrix_rhusiopathiae_GCF_900637845,${file_name}_rmdup,0,0" >> mapping/samples_modern.csv; done
echo "/ptmp/iclight/eager/mapping/zooscreen/easi241_for_erysipelothrix/results/trimmed_bam/,EASI241,Erysipelothrix_rhusiopathiae_GCF_900637845,EASI241.trimmed,0,0" >> mapping/samples_modern.csv

head -n1 mapping/samples.csv > header.csv
cat header.csv mapping/samples_modern.csv > mapping/samples.csv



ls -1 /ptmp/iclight/eager/mapping/zooscreen/other_ancient_seqs_for_erysipelothrix/results/trimmed_bam
"/ptmp/iclight/eager/mapping/zooscreen/easi241_for_erysipelothrix/results/trimmed_bam/,EASI241,Erysipelothrix_rhusiopathiae_GCF_900637845,EASI241.trimmed,0,0" >> mapping/samples_modern.csv



ls -1 /ptmp/iclight/eager/mapping/zooscreen/other_ancient_seqs_for_erysipelothrix/results/trimmed_bam/*.bam | sed 's#bam/#bam/,#g' | awk -F',' '{print $1, $2, "Erysipelothrix_rhusiopathiae_GCF_900637845,"$2",0,0"}' | sed 's/\.trimmed\.bam//1' | sed 's/\.bam//g' | sed 's/ /,/g' >> samples_tail.csv
ls -1 /ptmp/iclight/eager/mapping/zooscreen/modern_erysipelothrix_genbank_additional/results/deduplication/ | while read file_name; do echo "/ptmp/iclight/eager/mapping/zooscreen/modern_erysipelothrix_genbank/results/deduplication/$file_name/,$file_name,Erysipelothrix_rhusiopathiae_GCF_900637845,${file_name}_rmdup,0,0" >> mapping/samples.csv; done

